### PR TITLE
WIP: Initial operations

### PR DESCRIPTION
**Pull request by jose-gataca**
@JanLin I created a pull request to compare and comment issues on the API. It will be on Draft after having the model and the discussions solved.

### CODE REVIEW

**Comment by lalc** [comment]
I am missing a proposal on actual schema definition and is unclear what this PR is about. I am assuming you are suggesting a REST wrapper for management functions which can be used for achieving interoperability. 

Here is what I suggest as the next steps:

Step 01: Review the protocol specification and agree on the schema. 
Step 02: DID Comm protocol implementation
Step 03: Provide interface specs in folder /interface-specs (for management funcitons)
Step 04: Review and merge into a common generic interface.

iGrant.io approach is to use DIDComm is our primary interace with a REST wrapper around it for management functions. For example this could be used by implementation specific or at some point develop into a common component. 

Thoughts?

**Comment by jose-gataca** [comment]
Hi Lal,
For the schema, the goal is to use the Data Agreement document model. I have been asking @JanLin for an example, as all I have is the definition on the documentation, and I am not sure about the relation and cardinality of the different properties.

The goal of this API was to first provide a first version, REST-based, unrelated to DID-Comm. Have some interop-test results, then provide a seconde version on the API wrapping those messages under DID-Comm. In our thoughts, the Data Agreement model and protocol should be sufficient themselves, and agnostic to other stack layers such as DID-Comm.

Does it make sense?

**Comment by lalc** [comment]
Thanks for clarifying @jose-gataca. The approach is fine. However,  the starting point is to agree on the data agreement schema. This is already captured in the protocol specification today and please use that as the basis. 

In the PR, I do not see any Data Agreement schema. Or am I missing something? 

Its ok to put an early version, but please put it under [interface-specs](https://github.com/decentralised-dataexchange/automated-data-agreements/tree/main/interface-specs). ok?

**Comment by jose-gataca** [comment]
Hi, @lalc @JanLin:

I took the example from the spec, but it didn't match the definition of properties on the spec. I made a proposition, I included both an example and the associated Json Schema.

I also moved the API specification to the folder.

**Comment by lalc** [comment]
@jose-gataca May I please request only to add VUI API here as these are implementation specific interface specs. We will also add our admin interface specs here then.

**Pull request closed without merging**
