### PR TITLE
Authenticity field in DA conforms to Linked Data Proofs

### PR DESCRIPTION
**Pull request by georgejpadayatti**
Signed-off-by: George J Padayatti <george.padayatti@igrant.io>

### CODE REVIEW

**Review by lalc — APPROVED** [review]

**Review by lalc — COMMENTED** [review]
Is there a reason why the background is brown here? Could we align with the normal styling?

**Comment by georgejpadayatti** [comment]
@lalc brown ?

**Comment by georgejpadayatti** [comment]
@JanLin Based on your internal comments regarding the proof node. I have submitted an alternative proposal as PR #17

**Comment by georgejpadayatti** [comment]
Closing this PR since alternate proposal seems more appropriate.

**Pull request closed without merging**
